version: 2

jobs:
        build:
                machine: true
                steps:
                        - checkout
                        - run: make docker-build
                        - run: make build
                        - run: make phan
                        - run: make test
                        - run: |
                              if [ "${CIRCLE_BRANCH}" == "master" ]; then 
                                  docker login -u $DOCKER_USER -p $DOCKER_PASS
                                  docker push ircmaxell/php-compiler:16.04-dev
                                  docker push ircmaxell/php-compiler:16.04
                              fi
